export   const products = [
  {
    id: "2bdy77h72782u289uj9",
    name: "pineapple premium",
    price: 5.99,
    stock: 5,
    image: "pineapple-premium.png",
    slug: "pineapple-premium",
    quantity: "1 piece",
  },
  {
    id: "2cdy57h72782u289uj9",
    name: "persimon sharon",
    price: 4.99,
    stock: 5,
    image: "persimmon-sharon.png",
    slug: "persimon-sharon",
    quantity: "1 kg",
  },
  {
    id: "2dcr57h44782u289uj9",
    name: "mango royal",
    price: 9.99,
    stock: 5,
    image: "mango-royal.png",
    slug: "mango-royal",
    quantity: "1 piece",
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "pitahaya yellow",
    price: 9.49,
    stock: 0,
    image: "pitahaya-yellow.png",
    slug: "pitahaya-yellow",
    quantity: "1 piece",
  },
  {
    id: "2dcr57h44782u289uj2",
    name: "Longan",
    price: 4.39,
    stock: 4,
    image: "longan.png",
    slug: "longan",
    quantity: "1 kg",
    discount: 23,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "mandarin clementine",
    price: 1.49,
    stock: 0,
    image: "mandarin-clementine.png",
    slug: "mandarin-clementine",
    quantity: "1 kg",
    discount: 49,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "physalis",
    price: 2.49,
    stock: 4,
    image: "physalis.png",
    slug: "physalis",
    quantity: "1 kg",
    discount: 25,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "avocado",
    price: 4.99,
    stock: 5,
    image: "avocado.png",
    slug: "physalis",
    quantity: "1 kg",
    discount: 10,
  },
];

export const categories = [
  {
    id: 1,
    category: "Avocado",
    link: "/sale?category=avocado",
    image: "avocado-category.jpg",
  },
  {
    id: 2,
    category: "Pineapple",
    link: "/sale?category=pineapple",
    image: "pineapple-category.jpg",
  },
  {
    id: 3,
    category: "Watermelons and melons",
    link: "/sale?category=watermelons+and+melons",
    image: "melons-category.png",
  },
  {
    id: 4,
    category: "Mango",
    link: "/sale?category=mango",
    image: "mango-category.jpg",
  },
  {
    id: 5,
    category: "Citrus",
    link: "/sale?category=citrus",
    image: "citrus-category.jpg",
  },
];