export const products = [
  {
    id: "2bdy77h72782u289uj9",
    name: "pineapple premium",
    price: 5.99,
    stock: 5,
    image: "pineapple-premium.png",
    slug: "pineapple-premium",
    quantity: "1 piece",
  },
  {
    id: "2cdy57h72782u289uj9",
    name: "persimon sharon",
    price: 4.99,
    stock: 5,
    image: "persimmon-sharon.png",
    slug: "persimon-sharon",
    quantity: "1 kg",
  },
  {
    id: "2dcr57h44782u289uj9",
    name: "mango royal",
    price: 9.99,
    stock: 5,
    image: "mango-royal.png",
    slug: "mango-royal",
    quantity: "1 piece",
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "pitahaya yellow",
    price: 9.49,
    stock: 0,
    image: "pitahaya-yellow.png",
    slug: "pitahaya-yellow",
    quantity: "1 piece",
  },
  {
    id: "2dcr57h44782u289uj2",
    name: "Longan",
    price: 4.39,
    stock: 4,
    image: "longan.png",
    slug: "longan",
    quantity: "1 kg",
    discount: 23,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "mandarin clementine",
    price: 1.49,
    stock: 0,
    image: "mandarin-clementine.png",
    slug: "mandarin-clementine",
    quantity: "1 kg",
    discount: 49,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "physalis",
    price: 2.49,
    stock: 4,
    image: "physalis.png",
    slug: "physalis",
    quantity: "1 kg",
    discount: 25,
  },
  {
    id: "2ccr47h24782u289uj9",
    name: "avocado",
    price: 4.99,
    stock: 5,
    image: "avocado.png",
    slug: "physalis",
    quantity: "1 kg",
    discount: 10,
  },
];

export const categories = [
  {
    id: 1,
    category: "Avocado",
    link: "/sale?category=avocado",
    image: "avocado-category.jpg",
  },
  {
    id: 2,
    category: "Pineapple",
    link: "/sale?category=pineapple",
    image: "pineapple-category.jpg",
  },
  {
    id: 3,
    category: "Watermelons and melons",
    link: "/sale?category=watermelons+and+melons",
    image: "melons-category.png",
  },
  {
    id: 4,
    category: "Mango",
    link: "/sale?category=mango",
    image: "mango-category.jpg",
  },
  {
    id: 5,
    category: "Citrus",
    link: "/sale?category=citrus",
    image: "citrus-category.jpg",
  },
];

export const reviews = [
  {
    id: "1jduey388",
    author: "John Doe",
    date: "2021-09-27",
    rating: 4.2,
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium cumque itaque maiores sunt quia sint cum soluta dicta provident possimus.",
    likes: 5,
    dislikes: 0,
  },
  {
    id: "1jduey311",
    author: "Amanda Smith",
    date: "2021-08-15",
    rating: 4.5,
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium cumque itaque maiores sunt quia sint cum soluta dicta provident possimus.",
    likes: 3,
    dislikes: 1,
  },
  {
    id: "1jduey3c2",
    author: "Jane Doe",
    date: "2022-09-27",
    rating: 5,
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium cumque itaque maiores sunt quia sint cum soluta dicta provident possimus.",
    likes: 4,
    dislikes: 1,
  },
];

export const ratings = [
  0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
  1.7, 1.8, 1.9, 2, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1,
  3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7,
  4.8, 4.9, 5,
];
